[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"

# Solidity compiler settings
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "paris"

# Formatting
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

# Testing
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15 }

# Gas reporting
gas_reports = ["DelphAI"]

[profile.ci]
fuzz = { runs = 5000 }
invariant = { runs = 1000 }

[profile.lite]
optimizer = false
fuzz = { runs = 50 }

# RPC endpoints (add your own)
# [rpc_endpoints]
# mainnet = "${MAINNET_RPC_URL}"
# sepolia = "${SEPOLIA_RPC_URL}"
# arbitrum = "${ARBITRUM_RPC_URL}"
# optimism = "${OPTIMISM_RPC_URL}"

# Etherscan API keys (add your own)
# [etherscan]
# mainnet = { key = "${ETHERSCAN_API_KEY}" }
# sepolia = { key = "${ETHERSCAN_API_KEY}" }
# arbitrum = { key = "${ARBISCAN_API_KEY}" }
# optimism = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
